### ISSUE TITLE
Links with a hash symbol don't resolve

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-organisations#353] opened 2017-04-27 11:58 UTC
Follow-up-ticket of #337. If you follow the filter links on the result page you get no hits. Replacing the ```#``` in the URL gives the results. On the fly I didn't found other URLs with a ```#``` so I can't test if it's a problem for all #-URLs.

**Comment by fsteeg** [comment] 2017-06-29 08:00
Can't reproduce. If I understand the discussion in https://github.com/hbz/lobid-organisations/issues/337 correctly, the issue originates from a manually constructed query with missing escaping of the the `#`. Closing.

**Closed by fsteeg** 2017-06-29 08:00 UTC
Labels: bug
